import nodemailer from "nodemailer";

export async function POST(request) {
  try {
    const { name, email, phone, message } = await request.json();

    if (!name || !email || !message) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), { status: 400 });
    }

    // ✅ Microsoft 365 (Works360) SMTP configuration
    const transporter = nodemailer.createTransport({
      host: "smtp.office365.com",
      port: 587,
      secure: false, // must be false for port 587
      auth: {
        user: "support@works360.com", // Works360 sender email
        pass: "Welcome@2026!!", // use app password if MFA is enabled
      },
      tls: {
        ciphers: "SSLv3",
      },
    });

    // ✅ Verify SMTP connection
    await transporter.verify();
    console.log("✅ SMTP connection verified successfully.");

    // ✉️ 1. Send confirmation email to customer
    await transporter.sendMail({
      from: '"Meta Partner Demos Support" <support@works360.com>',
      to: email,
      subject: "Support Request Received - Meta Partner Demos",
      html: `
        <p>Hi ${name},</p>
        <p>Thank you for contacting <b>Meta Partner Demos</b>. We’ve received your request successfully.</p>
        <p>Our support team will get back to you within two working days.</p>
        <hr/>
        <p><b>Your message:</b><br/>${message}</p>
        <br/>
        <p>Best regards,<br/>Meta Partner Demos Support Team</p>
      `,
    });

    // ✉️ 2. Send admin notification email
    await transporter.sendMail({
      from: '"Meta Partner Demos Website" <support@works360.com>',
      to: "zeeshan@works360.com",
      subject: "New Support Query Received",
      html: `
        <h3>New Support Request</h3>
        <p><b>Name:</b> ${name}</p>
        <p><b>Email:</b> ${email}</p>
        <p><b>Phone:</b> ${phone || "N/A"}</p>
        <p><b>Message:</b><br/>${message}</p>
        <hr/>
        <p>This message was automatically generated by the Meta Partner Demos website.</p>
      `,
    });

    console.log("✅ Emails sent successfully.");
    return new Response(JSON.stringify({ message: "Emails sent successfully" }), { status: 200 });

  } catch (error) {
    console.error("❌ Error sending email:", error);
    return new Response(JSON.stringify({ error: "Failed to send email" }), { status: 500 });
  }
}
